DROP TABLE IF EXISTS artists;

CREATE TABLE artists (
    idArtist VARCHAR PRIMARY KEY,
    strArtist VARCHAR,
    strArtistStripped VARCHAR,
    strArtistAlternate VARCHAR,
    strLabel VARCHAR,
    idLabel VARCHAR,
    intFormedYear VARCHAR,
    intBornYear VARCHAR,
    intDiedYear VARCHAR,
    strDisbanded VARCHAR,
    strStyle VARCHAR,
    strGenre VARCHAR,
    strMood VARCHAR,
    strWebsite VARCHAR,
    strFacebook VARCHAR,
    strTwitter VARCHAR,
    strBiographyEN TEXT,
    strBiographyDE TEXT,
    strBiographyFR TEXT,
    strBiographyCN TEXT,
    strBiographyIT TEXT,
    strBiographyJP TEXT,
    strBiographyRU TEXT,
    strBiographyES TEXT,
    strBiographyPT TEXT,
    strBiographySE TEXT,
    strBiographyNL TEXT,
    strBiographyHU TEXT,
    strBiographyNO TEXT,
    strBiographyIL TEXT,
    strBiographyPL TEXT,
    strGender VARCHAR,
    intMembers VARCHAR,
    strCountry VARCHAR,
    strCountryCode VARCHAR,
    strArtistThumb VARCHAR,
    strArtistLogo VARCHAR,
    strArtistCutout VARCHAR,
    strArtistClearart VARCHAR,
    strArtistWideThumb VARCHAR,
    strArtistFanart VARCHAR,
    strArtistFanart2 VARCHAR,
    strArtistFanart3 VARCHAR,
    strArtistFanart4 VARCHAR,
    strArtistBanner VARCHAR,
    strMusicBrainzID VARCHAR,
    strISNIcode VARCHAR,
    strLastFMChart VARCHAR,
    intCharted VARCHAR,
    strLocked VARCHAR
);
