DROP TABLE IF EXISTS songs;

CREATE TABLE songs (
    idTrack VARCHAR PRIMARY KEY,
    idAlbum VARCHAR,
    idArtist VARCHAR,
    idLyric VARCHAR,
    idIMVDB VARCHAR,
    strTrack VARCHAR,
    strAlbum VARCHAR,
    strArtist VARCHAR,
    strArtistAlternate VARCHAR,
    intCD VARCHAR,
    intDuration VARCHAR,
    strGenre VARCHAR,
    strMood VARCHAR,
    strStyle VARCHAR,
    strTheme VARCHAR,
    strDescriptionEN TEXT,
    strDescriptionDE TEXT,
    strDescriptionFR TEXT,
    strDescriptionCN TEXT,
    strDescriptionIT TEXT,
    strDescriptionJP TEXT,
    strDescriptionRU TEXT,
    strDescriptionES TEXT,
    strDescriptionPT TEXT,
    strDescriptionSE TEXT,
    strDescriptionNL TEXT,
    strDescriptionHU TEXT,
    strDescriptionNO TEXT,
    strDescriptionIL TEXT,
    strDescriptionPL TEXT,
    strTrackThumb VARCHAR,
    strTrack3DCase VARCHAR,
    strTrackLyrics VARCHAR,
    strMusicVid VARCHAR,
    strMusicVidDirector VARCHAR,
    strMusicVidCompany VARCHAR,
    strMusicVidScreen1 VARCHAR,
    strMusicVidScreen2 VARCHAR,
    strMusicVidScreen3 VARCHAR,
    intMusicVidViews VARCHAR,
    intMusicVidLikes VARCHAR,
    intMusicVidDislikes VARCHAR,
    intMusicVidFavorites VARCHAR,
    intMusicVidComments VARCHAR,
    intTrackNumber VARCHAR,
    intLoved VARCHAR,
    intScore VARCHAR,
    intScoreVotes VARCHAR,
    intTotalListeners VARCHAR,
    intTotalPlays VARCHAR,
    strMusicBrainzID VARCHAR,
    strMusicBrainzAlbumID VARCHAR,
    strMusicBrainzArtistID VARCHAR,
    strLocked VARCHAR
);
